<a href="https://colab.research.google.com/github/RamSankarS/ML-GA-Motif-Discovery/blob/main/ace2motif.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install biopython scikit-learn xgboost seaborn tqdm datasets

Requirement already satisfied: biopython in /usr/local/lib/python3.11/dist-packages (1.85)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: xgboost in /usr/local/lib/python3.11/dist-packages (2.1.4)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (0.13.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Collecting datasets
  Downloading datasets-3.3.2-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from biopython) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost) (2.21.5)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.11/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.11/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py311-none-any.whl.metadata (7.2 kB)
Requirement already satisfied: fsspec<=2024.12.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.12.0,>=2023.1.0->datasets) (2024.10.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.13)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.6)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.12.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading datasets-3.3.2-py3-none-any.whl (485 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 26.1 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 8.0 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py311-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 10.6 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 14.3 MB/s eta 0:00:00
Installing collected packages: xxhash, dill, multiprocess, datasets
Successfully installed datasets-3.3.2 dill-0.3.8 multiprocess-0.70.16 xxhash-3.5.0

In [ ]:
from google.colab import files
import zipfile

uploaded_zip = files.upload()

zip_filename = 'covid19-ace2-variants.zip'
with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall('./covid19-ace2-variants.zip')

print("Folder extracted successfully.")

In [ ]:
import os
repo_dir = "covid19-ace2-variants/covid19-ace2-variants"
for root, dirs, files in os.walk(repo_dir):
    level = root.replace(repo_dir, "").count(os.sep)
    indent = " " * 4 * level
    print(f"{indent}{os.path.basename(root)}/")
    subindent = " " * 4 * (level + 1)
    for f in files:
        print(f"{subindent}{f}")

covid19-ace2-variants/
    LICENSE
    snp_table.csv
    ACE2_CDS.fa
    CITATION.bib
    proteofav.ipynb
    directory_structure.txt
    covid_project_utils.py
    README.md
    ACE2-variants-structure-and-assays.ipynb
    ACE2_HUMAN.fa
    codons.ipynb
    .git/
        packed-refs
        HEAD
        index
        config
        description
        refs/
            remotes/
                origin/
                    HEAD
            tags/
            heads/
                master
        info/
            exclude
        branches/
        logs/
            HEAD
            refs/
                remotes/
                    origin/
                        HEAD
                heads/
                    master
        objects/
            pack/
                pack-f57f803a3623f1cafb635f04f3d1fd24c0bb2de5.pack
                pack-f57f803a3623f1cafb635f04f3d1fd24c0bb2de5.idx
                pack-f57f803a3623f1cafb635f04f3d1fd24c0bb2de5.rev
            info/
        hooks/
            pre-push.sample
            pre-commit.sample
            push-to-checkout.sample
            pre-merge-commit.sample
            fsmonitor-watchman.sample
            commit-msg.sample
            pre-applypatch.sample
            sendemail-validate.sample
            update.sample
            pre-receive.sample
            pre-rebase.sample
            prepare-commit-msg.sample
            applypatch-msg.sample
            post-update.sample
    mutagenesis-assays/
        mutant-S1-Ig-association-from-Fig3-WebPlotDigitizer.json
        mutant-S1-Ig-association-from-Fig1-WebPlotDigitizer.json
        mutant-S1-Ig-association-from-Fig3.csv
        .gitignore
        mutant-S1-Ig-association-from-Fig1-singles.csv
    notebook_output/
        mCSM-PPI2-Prediction-vs-assayed-ROC.png
        mCSM-PPI2-interface-gnomAD.csv
        ddG-vs-distance-to-interface-all-gnomad.svg
        plot-assay-vs-rev-ddG.png
        README
        mCSM-PPI2-ddG-saturation-single-base-change.svg
        mCSM-PPI2-ddG-saturation.svg
        ddG-vs-distance-to-interface-all-gnomad.png
        plot-mutagenesis-assay-vs-prodigy.svg
        other_lof_variants.csv
        mCSM-PPI2-ddG-saturation-single-base-change-min.png
        plot-ddG-vs-R439N-ddG.png
        mCSM-PPI2-ddG-saturation.png
        ddG_all_gnomad_distribution.svg
        ACE2-Spike-interface-variants.csv
        plot-rev-ddG-roc.svg
        TMPRSS2_variants.csv
        variants_at_assayed_sites.csv
        ADAM17_variants.csv
        mCSM-PPI2-Prediction-vs-assayed-ROC.svg
        plot-rev-ddG-roc.png
        plot-assay-vs-rev-ddG.svg
        ~$ACE2-Spike-interface-residues.xlsx
        mCSM-PPI2-ddG-6vw1-vs-6lzg.png
        mutagenesis-transcribed-vs-description.svg
        ACE2-Spike-interface-residues.xlsx
        mCSM-PPI2-interface-gnomAD.xlsx
        mCSM-PPI2-ddG-saturation-single-base-change-min.svg
        plot-mutagenesis-assay-vs-prediction.png
        ddG_all_gnomad_distribution.png
        plot-ddG-vs-rev-ddG.png
        ACE2_gnomAD_variants.csv
        plot-ddG-vs-rev-ddG.svg
        mCSM-PPI2-ddG-saturation-single-base-change.png
        plot-mutagenesis-assay-vs-prodigy.png
        ACE2-Spike-interface-variants.xlsx
        mutagenesis-transcribed-vs-description.png
        plot-ddG-vs-R439N-ddG.svg
        mCSM-PPI2-extended-interface-gnomAD.csv
        plot-mutagenesis-assay-vs-prediction.svg
        mCSM-PPI2-extended-interface-gnomAD.xlsx
        mCSM-PPI2-ddG-6vw1-vs-6lzg.svg
        ACE2-Spike-interface-residues.csv
    MutaBind2/
        gnomAD-interface/
            MutaBind2.csv
        Bat/
            MutaBind2.csv
        gnomAD/
            MutaBind2.csv
        Pig/
            MutaBind2.csv
        alanine-scan/
            MutaBind2.csv
        Civet/
            MutaBind2.csv
        Mouse/
            MutaBind2.csv
        R439N-model/
            MutaBind2.csv
            gnomAD-interface/
                MutaBind2.csv
            gnomAD-extended-interface/
                MutaBind2.csv
            ortholog-single-submission/
                MutaBind2.csv
            alanine-scan/
                MutaBind2.csv
        6vw1-validation/
            MutaBind2.csv
        2ajf-validation/
            MutaBind2.csv
    PF01401/
        results/
            alignment_variants-sorted.vcf.gz.tbi
            alignment_variants-sorted.vcf.gz
    Prodigy/
        2ajf-mCSM-PPI2-models-binding-assay-mutants.csv
    hACE2-vs-orthologs/
        hACE2-vs-pigACE2.fa
        hACE2-vs-batACE2.fa
        hACE2-vs-civetACE2.fa
        Rhinolophus-alcyone/
            hACE2-vs-RHIAY.fa
    proteofav_db/
        Q9BYF1.gff
    mCSM-PPI2-Predictions/
        mCSM-PPI2-server-interface.csv
        6vw1/
            jobs/
                6vw1-ACE2-gnomAD.csv
                6vw1-ACE2-nCoV_S-gnomAD.csv
                6vw1-ACE2-nCoV_S-mutagenesis.csv
                saturation-scan/
                    6vw1-ACE2-S-Saturation-scan.csv
                    158551006069.csv
                saturation-G326/
                    158622661017.csv
                alanine-scan/
                    6vw1-ACE2-S-Alanine-scan.csv
                Italian-variants/
                    158706309585.csv
                binding-assay-mutants/
                    158557825833.csv
                civet-mutations/
                    158636685075-civet-mutations.csv
                all-gnomAD/
                    158557537205.csv
                gnomAD-ACE2-S-interface/
                    15855159013.csv
                saturation-G352/
                    158622689658.csv
                binding-assay-mutants-multi-single-point-sites/
                    158560454213.csv
        submission-lists/
            gnomAD-6vw1-interface-input.txt
            G352-saturation-list-input.txt
            italian-variants.txt
            civet_mutations.txt
            pig_mutations.txt
            gnomAD-6vw1-input.txt
            bat_mutations.txt
            G326-saturation-list-input.txt
        reverse-predictions/
            D355N-reverse/
                transcribed-prediction.csv
        6vw1-R439N-model/
            transcribed-prediction.csv
            gnomAD/
                158665174113.csv
            saturation-scan/
                158734016892.csv
            Italian-variants/
                158706342594.csv
            N439R-reverse-test/
                transcribed-prediction.csv
        6lzg/
            jobs/
                saturation-scan/
                    158733965972.csv
        2ajf-reverse-mutations/
            transcribed-predictions.csv
        2ajf/
            jobs/
                binding-assay-mutants-additional/
                    2ajf-ACE2-mutagenesis-suplementary.csv
                    15858472465.csv
                binding-assay-mutants/
                    2ajf-ACE2-nCoV_S-mutagenesis.csv
                    158560775724.csv
    hACE2-vs-mACE2/
        hACE2-vs-mACE2.fa

In [ ]:
import pandas as pd

# Adjust the path if needed.
snp_table_path = os.path.join(repo_dir, "snp_table.csv")
snp_df = pd.read_csv(snp_table_path)
print("First few rows of snp_table.csv:")
display(snp_df.head())

First few rows of snp_table.csv:

  from_codon to_codon from_aa to_aa  n_subs
0        TTT      TTC       F     F       1
1        TTT      TTA       F     L       1
2        TTT      TTG       F     L       1
3        TTT      TCT       F     S       1
4        TTT      TAT       F     Y       1

In [ ]:
from Bio import SeqIO

# Load ACE2_CDS.fa
cds_fasta_path = os.path.join(repo_dir, "ACE2_CDS.fa")
cds_records = list(SeqIO.parse(cds_fasta_path, "fasta"))
print(f"Found {len(cds_records)} record(s) in ACE2_CDS.fa.")
print("First record:")
print(cds_records[0].format("fasta"))

# Load ACE2_HUMAN.fa
human_fasta_path = os.path.join(repo_dir, "ACE2_HUMAN.fa")
human_records = list(SeqIO.parse(human_fasta_path, "fasta"))
print(f"\nFound {len(human_records)} record(s) in ACE2_HUMAN.fa.")
print("First record:")
print(human_records[0].format("fasta"))

Found 1 record(s) in ACE2_CDS.fa.
First record:
>CDS|ENST00000427411/1-2415
ATGTCAAGCTCTTCCTGGCTCCTTCTCAGCCTTGTTGCTGTAACTGCTGCTCAGTCCACC
ATTGAGGAACAGGCCAAGACATTTTTGGACAAGTTTAACCACGAAGCCGAAGACCTGTTC
TATCAAAGTTCACTTGCTTCTTGGAATTATAACACCAATATTACTGAAGAGAATGTCCAA
AACATGAATAATGCTGGGGACAAATGGTCTGCCTTTTTAAAGGAACAGTCCACACTTGCC
CAAATGTATCCACTACAAGAAATTCAGAATCTCACAGTCAAGCTTCAGCTGCAGGCTCTT
CAGCAAAATGGGTCTTCAGTGCTCTCAGAAGACAAGAGCAAACGGTTGAACACAATTCTA
AATACAATGAGCACCATCTACAGTACTGGAAAAGTTTGTAACCCAGATAATCCACAAGAA
TGCTTATTACTTGAACCAGGTTTGAATGAAATAATGGCAAACAGTTTAGACTACAATGAG
AGGCTCTGGGCTTGGGAAAGCTGGAGATCTGAGGTCGGCAAGCAGCTGAGGCCATTATAT
GAAGAGTATGTGGTCTTGAAAAATGAGATGGCAAGAGCAAATCATTATGAGGACTATGGG
GATTATTGGAGAGGAGACTATGAAGTAAATGGGGTAGATGGCTATGACTACAGCCGCGGC
CAGTTGATTGAAGATGTGGAACATACCTTTGAAGAGATTAAACCATTATATGAACATCTT
CATGCCTATGTGAGGGCAAAGTTGATGAATGCCTATCCTTCCTATATCAGTCCAATTGGA
TGCCTCCCTGCTCATTTGCTTGGTGATATGTGGGGTAGATTTTGGACAAATCTGTACTCT
TTGACAGTTCCCTTTGGACAGAAACCAAACATAGATGTTACTGATGCAATGGTGGACCAG
GCCTGGGATGCACAGAGAATATTCAAGGAGGCCGAGAAGTTCTTTGTATCTGTTGGTCTT
CCTAATATGACTCAAGGATTCTGGGAAAATTCCATGCTAACGGACCCAGGAAATGTTCAG
AAAGCAGTCTGCCATCCCACAGCTTGGGACCTGGGGAAGGGCGACTTCAGGATCCTTATG
TGCACAAAGGTGACAATGGACGACTTCCTGACAGCTCATCATGAGATGGGGCATATCCAG
TATGATATGGCATATGCTGCACAACCTTTTCTGCTAAGAAATGGAGCTAATGAAGGATTC
CATGAAGCTGTTGGGGAAATCATGTCACTTTCTGCAGCCACACCTAAGCATTTAAAATCC
ATTGGTCTTCTGTCACCCGATTTTCAAGAAGACAATGAAACAGAAATAAACTTCCTGCTC
AAACAAGCACTCACGATTGTTGGGACTCTGCCATTTACTTACATGTTAGAGAAGTGGAGG
TGGATGGTCTTTAAAGGGGAAATTCCCAAAGACCAGTGGATGAAAAAGTGGTGGGAGATG
AAGCGAGAGATAGTTGGGGTGGTGGAACCTGTGCCCCATGATGAAACATACTGTGACCCC
GCATCTCTGTTCCATGTTTCTAATGATTACTCATTCATTCGATATTACACAAGGACCCTT
TACCAATTCCAGTTTCAAGAAGCACTTTGTCAAGCAGCTAAACATGAAGGCCCTCTGCAC
AAATGTGACATCTCAAACTCTACAGAAGCTGGACAGAAACTGTTCAATATGCTGAGGCTT
GGAAAATCAGAACCCTGGACCCTAGCATTGGAAAATGTTGTAGGAGCAAAGAACATGAAT
GTAAGGCCACTGCTCAACTACTTTGAGCCCTTATTTACCTGGCTGAAAGACCAGAACAAG
AATTCTTTTGTGGGATGGAGTACCGACTGGAGTCCATATGCAGACCAAAGCATCAAAGTG
AGGATAAGCCTAAAATCAGCTCTTGGAGATAAAGCATATGAATGGAACGACAATGAAATG
TACCTGTTCCGATCATCTGTTGCATATGCTATGAGGCAGTACTTTTTAAAAGTAAAAAAT
CAGATGATTCTTTTTGGGGAGGAGGATGTGCGAGTGGCTAATTTGAAACCAAGAATCTCC
TTTAATTTCTTTGTCACTGCACCTAAAAATGTGTCTGATATCATTCCTAGAACTGAAGTT
GAAAAGGCCATCAGGATGTCCCGGAGCCGTATCAATGATGCTTTCCGTCTGAATGACAAC
AGCCTAGAGTTTCTGGGGATACAGCCAACACTTGGACCTCCTAACCAGCCCCCTGTTTCC
ATATGGCTGATTGTTTTTGGAGTTGTGATGGGAGTGATAGTGGTTGGCATTGTCATCCTG
ATCTTCACTGGGATCAGAGATCGGAAGAAGAAAAATAAAGCAAGAAGTGGAGAAAATCCT
TATGCCTCCATCGATATTAGCAAAGGAGAAAATAATCCAGGATTCCAAAACACTGATGAT
GTTCAGACCTCCTTT


Found 1 record(s) in ACE2_HUMAN.fa.
First record:
>ACE2_HUMAN/1-805 Angiotensin-converting enzyme 2
MSSSSWLLLSLVAVTAAQSTIEEQAKTFLDKFNHEAEDLFYQSSLASWNYNTNITEENVQ
NMNNAGDKWSAFLKEQSTLAQMYPLQEIQNLTVKLQLQALQQNGSSVLSEDKSKRLNTIL
NTMSTIYSTGKVCNPDNPQECLLLEPGLNEIMANSLDYNERLWAWESWRSEVGKQLRPLY
EEYVVLKNEMARANHYEDYGDYWRGDYEVNGVDGYDYSRGQLIEDVEHTFEEIKPLYEHL
HAYVRAKLMNAYPSYISPIGCLPAHLLGDMWGRFWTNLYSLTVPFGQKPNIDVTDAMVDQ
AWDAQRIFKEAEKFFVSVGLPNMTQGFWENSMLTDPGNVQKAVCHPTAWDLGKGDFRILM
CTKVTMDDFLTAHHEMGHIQYDMAYAAQPFLLRNGANEGFHEAVGEIMSLSAATPKHLKS
IGLLSPDFQEDNETEINFLLKQALTIVGTLPFTYMLEKWRWMVFKGEIPKDQWMKKWWEM
KREIVGVVEPVPHDETYCDPASLFHVSNDYSFIRYYTRTLYQFQFQEALCQAAKHEGPLH
KCDISNSTEAGQKLFNMLRLGKSEPWTLALENVVGAKNMNVRPLLNYFEPLFTWLKDQNK
NSFVGWSTDWSPYADQSIKVRISLKSALGDKAYEWNDNEMYLFRSSVAYAMRQYFLKVKN
QMILFGEEDVRVANLKPRISFNFFVTAPKNVSDIIPRTEVEKAIRMSRSRINDAFRLNDN
SLEFLGIQPTLGPPNQPPVSIWLIVFGVVMGVIVVGIVILIFTGIRDRKKKNKARSGENP
YASIDISKGENNPGFQNTDDVQTSF

In [ ]:
import glob
import os
import pandas as pd

# Construct the search pattern to find all MutaBind2.csv files recursively
mutabind_pattern = os.path.join(repo_dir, "MutaBind2", "**", "MutaBind2.csv")
mutabind_csv_files = glob.glob(mutabind_pattern, recursive=True)
print("Found MutaBind2 CSV files:")
print(mutabind_csv_files)

# Read and combine all MutaBind2.csv files, skipping the first row in each file.
mutabind_dfs = []
for file in mutabind_csv_files:
    # Skip the first row which contains the title.
    df = pd.read_csv(file, skiprows=1)
    # Extract the parent folder name as a category identifier.
    parent_folder = os.path.basename(os.path.dirname(file))
    df["category"] = parent_folder
    mutabind_dfs.append(df)

if mutabind_dfs:
    combined_mutabind = pd.concat(mutabind_dfs, ignore_index=True)
    print("Combined MutaBind2 predictions (first 5 rows):")
    display(combined_mutabind.head())
else:
    print("No MutaBind2 CSV files found.")

Found MutaBind2 CSV files:
['covid19-ace2-variants/covid19-ace2-variants/MutaBind2/gnomAD-interface/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/Bat/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/gnomAD/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/Pig/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/alanine-scan/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/Civet/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/Mouse/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/R439N-model/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/R439N-model/gnomAD-interface/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/R439N-model/gnomAD-extended-interface/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/R439N-model/ortholog-single-submission/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/R439N-model/alanine-scan/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/6vw1-validation/MutaBind2.csv', 'covid19-ace2-variants/covid19-ace2-variants/MutaBind2/2ajf-validation/MutaBind2.csv']
Combined MutaBind2 predictions (first 5 rows):

  Mutated Chain Mutation   DDG Interface?  ... Model_Bias          category  Mutation ID  dE_vdw_wt
0             A     S19P  0.08        yes  ...     0.4286  gnomAD-interface          NaN        NaN
1             A     T27A  0.64        yes  ...     0.4286  gnomAD-interface          NaN        NaN
2             A     E35K  0.38        yes  ...     0.4286  gnomAD-interface          NaN        NaN
3             A     E37K  0.96        yes  ...     0.4286  gnomAD-interface          NaN        NaN
4             A     M82I  0.23        yes  ...     0.4286  gnomAD-interface          NaN        NaN

[5 rows x 17 columns]

In [ ]:
from Bio import SeqIO
from Bio.Data import CodonTable
import pandas as pd

# 1. Load the ACE2 coding sequence
ace2_cds_path = "ACE2_CDS.fa"  # Adjust if needed
ace2_record = list(SeqIO.parse(ace2_cds_path, "fasta"))[0]  # assume only one record in the FASTA
ace2_seq = str(ace2_record.seq).upper()

# 2. Split into codons
codons = [ace2_seq[i : i+3] for i in range(0, len(ace2_seq), 3)]

# 3. Translate each codon to get the reference amino acid
standard_table = CodonTable.unambiguous_dna_by_id[1]  # Standard table, ID=1

def translate_codon(codon):
    """Translate a 3-nt codon into an amino acid (single letter).
       Returns '*' for stop codons or 'X' if not found."""
    # Some codons might be ambiguous; handle with get().
    return standard_table.forward_table.get(codon,
           standard_table.stop_codons and '*')

# Build a reference DataFrame mapping each codon index to (codon, amino_acid)
codon_df = pd.DataFrame({
    "codon_index": range(1, len(codons) + 1),
    "ref_codon": codons
})
codon_df["ref_aa"] = codon_df["ref_codon"].apply(translate_codon)

print("Reference codon table (first 10 rows):")
display(codon_df.head(10))

Reference codon table (first 10 rows):

   codon_index ref_codon ref_aa
0            1       ATG      M
1            2       TCA      S
2            3       AGC      S
3            4       TCT      S
4            5       TCC      S
5            6       TGG      W
6            7       CTC      L
7            8       CTT      L
8            9       CTC      L
9           10       AGC      S

In [ ]:
# Determine which columns correspond to mutations.
# Here, we assume 'WT' and 'source_file' are non-mutation columns.
assay_cols = [col for col in combined_assays.columns if col.strip() not in ['WT', 'source_file']]
print("Assay mutation columns detected:", assay_cols)

# Pivot the experimental assay data to long format:
assay_long = combined_assays.melt(id_vars=['WT', 'source_file'],
                                  value_vars=assay_cols,
                                  var_name='mutation',
                                  value_name='binding_affinity')

print("Experimental assay data in long format:")
display(assay_long.head())

Assay mutation columns detected: [' 97', 'P84S', ' 82']
Experimental assay data in long format:

     WT                             source_file mutation binding_affinity
0  K31D  mutant-S1-Ig-association-from-Fig3.csv       97              2.0
1  E37A  mutant-S1-Ig-association-from-Fig3.csv       97             94.0
2  D38A  mutant-S1-Ig-association-from-Fig3.csv       97             90.0
3  Y41A  mutant-S1-Ig-association-from-Fig3.csv       97             12.0
4  K68D  mutant-S1-Ig-association-from-Fig3.csv       97             72.0

In [ ]:
snp_df = snp_df.rename(columns={
    "from_codon": "snp_from_codon",
    "to_codon":   "snp_to_codon",
    "from_aa":    "snp_from_aa",
    "to_aa":      "snp_to_aa"
})
print("SNP table:")
display(snp_df.head(10))

SNP table:

  snp_from_codon snp_to_codon snp_from_aa snp_to_aa  n_subs mutation mutation_base
0            TTT          TTC           F         F       1      F1F            F1
1            TTT          TTA           F         L       1      F1L            F1
2            TTT          TTG           F         L       1      F1L            F1
3            TTT          TCT           F         S       1      F1S            F1
4            TTT          TAT           F         Y       1      F1Y            F1
5            TTT          TGT           F         C       1      F1C            F1
6            TTT          CTT           F         L       1      F1L            F1
7            TTT          ATT           F         I       1      F1I            F1
8            TTT          GTT           F         V       1      F1V            F1
9            TTC          TTT           F         F       1      F1F            F1

In [ ]:
def find_positions_for_snp(row, codon_df):
    """
    Given a row with (snp_from_codon, snp_from_aa, snp_to_codon, snp_to_aa),
    return all possible codon_index positions in codon_df that match the 'from' codon/AA.
    Also verify that to_codon translates to to_aa for consistency.
    """
    from_codon = row["snp_from_codon"]
    from_aa    = row["snp_from_aa"]
    to_codon   = row["snp_to_codon"]
    to_aa      = row["snp_to_aa"]

    # Check that to_codon -> to_aa is consistent
    # If it's not, we might as well return an empty list
    if translate_codon(to_codon) != to_aa:
        return []

    # Filter codon_df where reference codon == from_codon AND reference AA == from_aa
    matches = codon_df[
        (codon_df["ref_codon"] == from_codon) &
        (codon_df["ref_aa"] == from_aa)
    ]

    # Return the list of matching indices
    return list(matches["codon_index"])

# Apply this to each row in snp_df
all_positions = []
for i, row in snp_df.iterrows():
    positions = find_positions_for_snp(row, codon_df)
    # If no positions, we skip or note it
    # If multiple positions, we create multiple rows
    if len(positions) == 0:
        # Could store a placeholder or skip
        all_positions.append({
            **row.to_dict(),
            "codon_index": None  # no match
        })
    else:
        # For each matching position, create a row
        for pos in positions:
            new_row = {**row.to_dict(), "codon_index": pos}
            all_positions.append(new_row)

# Create a new DataFrame with codon_index appended
snp_positions_df = pd.DataFrame(all_positions)
print("SNP table with potential codon positions:")
display(snp_positions_df.head(20))

SNP table with potential codon positions:

   snp_from_codon snp_to_codon snp_from_aa snp_to_aa  n_subs mutation mutation_base  codon_index
0             TTT          TTC           F         F       1      F1F            F1         28.0
1             TTT          TTC           F         F       1      F1F            F1         32.0
2             TTT          TTC           F         F       1      F1F            F1         72.0
3             TTT          TTC           F         F       1      F1F            F1        230.0
4             TTT          TTC           F         F       1      F1F            F1        274.0
5             TTT          TTC           F         F       1      F1F            F1        285.0
6             TTT          TTC           F         F       1      F1F            F1        315.0
7             TTT          TTC           F         F       1      F1F            F1        390.0
8             TTT          TTC           F         F       1      F1F            F1        428.0
9             TTT          TTC           F         F       1      F1F            F1        452.0
10            TTT          TTC           F         F       1      F1F            F1        464.0
11            TTT          TTC           F         F       1      F1F            F1        525.0
12            TTT          TTC           F         F       1      F1F            F1        588.0
13            TTT          TTC           F         F       1      F1F            F1        592.0
14            TTT          TTC           F         F       1      F1F            F1        603.0
15            TTT          TTC           F         F       1      F1F            F1        655.0
16            TTT          TTC           F         F       1      F1F            F1        665.0
17            TTT          TTC           F         F       1      F1F            F1        681.0
18            TTT          TTC           F         F       1      F1F            F1        684.0
19            TTT          TTC           F         F       1      F1F            F1        724.0

In [ ]:
def make_protein_mutation_label(row):
    # e.g. from_aa = 'F', codon_index = 84, to_aa = 'S' -> "F84S"
    if pd.isna(row["codon_index"]):
        return None
    return f"{row['snp_from_aa']}{row['codon_index']}{row['snp_to_aa']}"

snp_positions_df["mutation"] = snp_positions_df.apply(make_protein_mutation_label, axis=1)

print("SNP table with standard protein mutation labels:")
display(snp_positions_df.head(20))

SNP table with standard protein mutation labels:

   snp_from_codon snp_to_codon snp_from_aa snp_to_aa  n_subs mutation mutation_base  codon_index
0             TTT          TTC           F         F       1   F28.0F            F1         28.0
1             TTT          TTC           F         F       1   F32.0F            F1         32.0
2             TTT          TTC           F         F       1   F72.0F            F1         72.0
3             TTT          TTC           F         F       1  F230.0F            F1        230.0
4             TTT          TTC           F         F       1  F274.0F            F1        274.0
5             TTT          TTC           F         F       1  F285.0F            F1        285.0
6             TTT          TTC           F         F       1  F315.0F            F1        315.0
7             TTT          TTC           F         F       1  F390.0F            F1        390.0
8             TTT          TTC           F         F       1  F428.0F            F1        428.0
9             TTT          TTC           F         F       1  F452.0F            F1        452.0
10            TTT          TTC           F         F       1  F464.0F            F1        464.0
11            TTT          TTC           F         F       1  F525.0F            F1        525.0
12            TTT          TTC           F         F       1  F588.0F            F1        588.0
13            TTT          TTC           F         F       1  F592.0F            F1        592.0
14            TTT          TTC           F         F       1  F603.0F            F1        603.0
15            TTT          TTC           F         F       1  F655.0F            F1        655.0
16            TTT          TTC           F         F       1  F665.0F            F1        665.0
17            TTT          TTC           F         F       1  F681.0F            F1        681.0
18            TTT          TTC           F         F       1  F684.0F            F1        684.0
19            TTT          TTC           F         F       1  F724.0F            F1        724.0

In [ ]:
non_synonymous = snp_positions_df[snp_positions_df["snp_from_aa"] != snp_positions_df["snp_to_aa"]]

print(f"Total non-synonymous mutations found: {len(non_synonymous)}")
display(non_synonymous.head(20))

Total non-synonymous mutations found: 5401

   snp_from_codon snp_to_codon snp_from_aa snp_to_aa  n_subs mutation mutation_base  codon_index
22            TTT          TTA           F         L       1   F28.0L            F1         28.0
23            TTT          TTA           F         L       1   F32.0L            F1         32.0
24            TTT          TTA           F         L       1   F72.0L            F1         72.0
25            TTT          TTA           F         L       1  F230.0L            F1        230.0
26            TTT          TTA           F         L       1  F274.0L            F1        274.0
27            TTT          TTA           F         L       1  F285.0L            F1        285.0
28            TTT          TTA           F         L       1  F315.0L            F1        315.0
29            TTT          TTA           F         L       1  F390.0L            F1        390.0
30            TTT          TTA           F         L       1  F428.0L            F1        428.0
31            TTT          TTA           F         L       1  F452.0L            F1        452.0
32            TTT          TTA           F         L       1  F464.0L            F1        464.0
33            TTT          TTA           F         L       1  F525.0L            F1        525.0
34            TTT          TTA           F         L       1  F588.0L            F1        588.0
35            TTT          TTA           F         L       1  F592.0L            F1        592.0
36            TTT          TTA           F         L       1  F603.0L            F1        603.0
37            TTT          TTA           F         L       1  F655.0L            F1        655.0
38            TTT          TTA           F         L       1  F665.0L            F1        665.0
39            TTT          TTA           F         L       1  F681.0L            F1        681.0
40            TTT          TTA           F         L       1  F684.0L            F1        684.0
41            TTT          TTA           F         L       1  F724.0L            F1        724.0

In [ ]:
# Create a mutation_base column in the mCSM-PPI2 predictions DataFrame
combined_mcsm['mutation_base'] = combined_mcsm['wild-type'] + combined_mcsm['res-number'].astype(str)

print("mCSM-PPI2 predictions after adding mutation_base:")
display(combined_mcsm.head())
combined_mcsm

mCSM-PPI2 predictions after adding mutation_base:

  chain wild-type  res-number  distance-to-interface                     source_file mutation_base
0     A       SER          19                  2.631  mCSM-PPI2-server-interface.csv         SER19
1     A       GLN          24                  3.031  mCSM-PPI2-server-interface.csv         GLN24
2     A       THR          27                  3.703  mCSM-PPI2-server-interface.csv         THR27
3     A       PHE          28                  3.376  mCSM-PPI2-server-interface.csv         PHE28
4     A       ASP          30                  4.116  mCSM-PPI2-server-interface.csv         ASP30

   chain wild-type  res-number  distance-to-interface                     source_file mutation_base
0      A       SER          19                  2.631  mCSM-PPI2-server-interface.csv         SER19
1      A       GLN          24                  3.031  mCSM-PPI2-server-interface.csv         GLN24
2      A       THR          27                  3.703  mCSM-PPI2-server-interface.csv         THR27
3      A       PHE          28                  3.376  mCSM-PPI2-server-interface.csv         PHE28
4      A       ASP          30                  4.116  mCSM-PPI2-server-interface.csv         ASP30
5      A       LYS          31                  2.925  mCSM-PPI2-server-interface.csv         LYS31
6      A       HIS          34                  3.049  mCSM-PPI2-server-interface.csv         HIS34
7      A       GLU          35                  2.933  mCSM-PPI2-server-interface.csv         GLU35
8      A       GLU          37                  3.185  mCSM-PPI2-server-interface.csv         GLU37
9      A       ASP          38                  2.991  mCSM-PPI2-server-interface.csv         ASP38
10     A       TYR          41                  2.623  mCSM-PPI2-server-interface.csv         TYR41
11     A       GLN          42                  3.094  mCSM-PPI2-server-interface.csv         GLN42
12     A       LEU          45                  3.851  mCSM-PPI2-server-interface.csv         LEU45
13     A       LEU          79                  3.541  mCSM-PPI2-server-interface.csv         LEU79
14     A       MET          82                  3.481  mCSM-PPI2-server-interface.csv         MET82
15     A       TYR          83                  2.933  mCSM-PPI2-server-interface.csv         TYR83
16     A       GLY         326                  5.538  mCSM-PPI2-server-interface.csv        GLY326
17     A       GLU         329                  4.056  mCSM-PPI2-server-interface.csv        GLU329
18     A       ASN         330                  3.617  mCSM-PPI2-server-interface.csv        ASN330
19     A       GLY         352                  5.412  mCSM-PPI2-server-interface.csv        GLY352
20     A       LYS         353                  2.820  mCSM-PPI2-server-interface.csv        LYS353
21     A       GLY         354                  3.447  mCSM-PPI2-server-interface.csv        GLY354
22     A       ASP         355                  3.475  mCSM-PPI2-server-interface.csv        ASP355
23     A       ARG         357                  3.595  mCSM-PPI2-server-interface.csv        ARG357
24     A       ARG         393                  3.533  mCSM-PPI2-server-interface.csv        ARG393
25     E       ARG         439                  4.056  mCSM-PPI2-server-interface.csv        ARG439
26     E       THR         446                  4.919  mCSM-PPI2-server-interface.csv        THR446
27     E       TYR         449                  2.991  mCSM-PPI2-server-interface.csv        TYR449
28     E       TYR         453                  3.049  mCSM-PPI2-server-interface.csv        TYR453
29     E       LEU         455                  3.450  mCSM-PPI2-server-interface.csv        LEU455
30     E       PHE         456                  3.703  mCSM-PPI2-server-interface.csv        PHE456
31     E       TYR         473                  4.843  mCSM-PPI2-server-interface.csv        TYR473
32     E       ALA         475                  2.631  mCSM-PPI2-server-interface.csv        ALA475
33     E       GLY         476                  3.828  mCSM-PPI2-server-interface.csv        GLY476
34     E       SER         477                  4.464  mCSM-PPI2-server-interface.csv        SER477
35     E       PHE         486                  3.342  mCSM-PPI2-server-interface.csv        PHE486
36     E       ASN         487                  2.933  mCSM-PPI2-server-interface.csv        ASN487
37     E       TYR         489                  3.031  mCSM-PPI2-server-interface.csv        TYR489
38     E       PHE         490                  4.175  mCSM-PPI2-server-interface.csv        PHE490
39     E       LEU         492                  4.715  mCSM-PPI2-server-interface.csv        LEU492
40     E       GLN         493                  2.925  mCSM-PPI2-server-interface.csv        GLN493
41     E       GLY         496                  2.980  mCSM-PPI2-server-interface.csv        GLY496
42     E       PHE         497                  4.837  mCSM-PPI2-server-interface.csv        PHE497
43     E       GLN         498                  3.094  mCSM-PPI2-server-interface.csv        GLN498
44     E       THR         500                  2.623  mCSM-PPI2-server-interface.csv        THR500
45     E       ASN         501                  3.277  mCSM-PPI2-server-interface.csv        ASN501
46     E       GLY         502                  2.820  mCSM-PPI2-server-interface.csv        GLY502
47     E       TYR         505                  3.185  mCSM-PPI2-server-interface.csv        TYR505

In [ ]:
from Bio import SeqUtils

# Convert single-letter amino acid codes to three-letter codes
def convert_aa(single_letter):
    try:
        return SeqUtils.IUPACData.protein_letters_1to3[single_letter.upper()].upper()
    except KeyError:
        return None  # Handle unexpected characters

# Apply conversion to snp_positions_df to match mCSM-PPI2 format
snp_positions_df["wild-type"] = snp_positions_df["snp_from_aa"].apply(convert_aa)
snp_positions_df["mutation_base"] = snp_positions_df["wild-type"] + snp_positions_df["codon_index"].fillna(0).astype(int).astype(str)

# Merge with mCSM-PPI2 predictions
df_merged = snp_positions_df.merge(combined_mcsm, on="mutation_base", how="left")

# Display summary
print(f"Total SNP mutations matched with structural predictions: {df_merged['mutation_base'].notna().sum()} out of {len(snp_positions_df)}")
display(df_merged.head(20))

Total SNP mutations matched with structural predictions: 6925 out of 6925

   snp_from_codon snp_to_codon  ... distance-to-interface                     source_file
0             TTT          TTC  ...                 3.376  mCSM-PPI2-server-interface.csv
1             TTT          TTC  ...                   NaN                             NaN
2             TTT          TTC  ...                   NaN                             NaN
3             TTT          TTC  ...                   NaN                             NaN
4             TTT          TTC  ...                   NaN                             NaN
5             TTT          TTC  ...                   NaN                             NaN
6             TTT          TTC  ...                   NaN                             NaN
7             TTT          TTC  ...                   NaN                             NaN
8             TTT          TTC  ...                   NaN                             NaN
9             TTT          TTC  ...                   NaN                             NaN
10            TTT          TTC  ...                   NaN                             NaN
11            TTT          TTC  ...                   NaN                             NaN
12            TTT          TTC  ...                   NaN                             NaN
13            TTT          TTC  ...                   NaN                             NaN
14            TTT          TTC  ...                   NaN                             NaN
15            TTT          TTC  ...                   NaN                             NaN
16            TTT          TTC  ...                   NaN                             NaN
17            TTT          TTC  ...                   NaN                             NaN
18            TTT          TTC  ...                   NaN                             NaN
19            TTT          TTC  ...                   NaN                             NaN

[20 rows x 14 columns]